#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test $(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
	exit 1
fi

# 12/7/26 DH: Testing pre-commit hook prior to adding to 'camera-gapp' to check url's removed
#             This needs to be added with: git config --local core.hooksPath .githooks
#
#             Add it to ~/.gitconfig with: git config --global core.hooksPath .githooks
# -------------------------------------------------------------------------------------------
topLevel=$(git rev-parse --show-toplevel)

# 13/7/26 DH: 'xargs' strips leading whitespace from strings
url1Str=$(grep 'public url1' $topLevel/src/app/services/appscript.service.ts | xargs)
url2Str=$(grep 'public url2' $topLevel/src/app/services/appscript.service.ts | xargs)

url1StrEmpty="public url1 = '';"
url2StrEmpty="public url2 = '';"

if (( ${#url1Str} > ${#url1StrEmpty} ))
then
  echo "url1Str Len: " ${#url1Str}
  echo "url1StrEmpty Len: " ${#url1StrEmpty}
  echo "url1 not empty"
  echo $url1Str
  echo
  exit 1
fi

if (( ${#url2Str} > ${#url2StrEmpty} ))
then
  echo "url2 not empty"
  echo $url2Str
  echo
  exit 1
fi
# -------------------------------------------------------------------------------------------

###########################################################################################################
# 12/7/26 DH: exec = "Execute command in place of the current process (instead of creating a new process)"
#             This means that commands after the "exec" will not be run after command returns...!
#
#             It ensures that return value from 'git diff-index' will be return value from 'pre-commit'
###########################################################################################################

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --
